.TH AUTOEHD 8 "14 April 2003"
.SH NAME
autoehd - mount the EHD of a user that is defined in pam_mount.conf
.SH SYNOPSIS
\fBautoehd\fP [\fIuser\fP] [\fIoptions\fP]...
.SH OPTIONS
.TP
\fB\-h\fP,\fB\-?\fP
display help
.SH AUTHOR
This manpage was originally written by Bastian Kleineidam <calvin@debian.org>
for the Debian distribution of pam_mount (libpam\-mount) but may be used by
others.

See /usr/share/doc/packages/pam_mount/AUTHORS for the list of original authors
of pam_mount.
