.TH mount_ehd 8 "30 January 2003"
.SH NAME
mount_ehd - mount a users's efsk
.SH SYNOPSIS
\fBmount_ehd\fP [\fIuser\fP] [\fIoption\fP]...
.SH OPTIONS
.TP
\fB\-h\fP, \fB\-?\fP
display help
.SH AUTHOR
This manpage was originally written by Bastian Kleineidam <calvin@debian.org>
for the Debian distribution of pam_mount (libpam\-mount) but may be used by
others.

See /usr/share/doc/packages/pam_mount/AUTHORS for the list of original authors
of pam_mount.
