.TH AUTOEHD 8 "14 April 2003"
.SH NAME
autoehd - mount the encrypted home directory of a user
.SH SYNOPSIS
\fBautoehd\fP [\fIuser\fP] [\fIoptions\fP]...
.SH DESCRIPTION
Mounts the encrypted home directory defined in \fBpam_mount.conf.xml\fP for the
given user.
.SH OPTIONS
.TP
\fB\-h\fP,\fB\-?\fP
display help
.SH AUTHOR
This manpage was originally written by Bastian Kleineidam <calvin@debian.org>
for the Debian distribution of pam_mount (libpam\-mount) but may be used by
others.

See /usr/share/doc/packages/pam_mount/AUTHORS for the list of original authors
of pam_mount.
