.TH mount.crypt 8 "2008\-10\-08" "pam_mount" "pam_mount"
.SH Name
mount.crypt - mount a dm\-crypt encrypted volume
.SH Syntax
\fBmount.crypt\fP [\fB-n\fP] [\fB\-o\fP \fIoptions\fP]
\fIdevice\fP \fIdirectory\fP
.SH Options
.TP
\fB\-o\fP \fIoptions\fP
Set the mount options. mount.crypt will take out its own options it recognizes
and passes any remaining options on to the underlying mount program.
.TP
\fB\-n\fP
Do not update /etc/mtab. Note that this makes it impossible to unmount the
volume by naming the container - you will have to pass the mountpoint to
umount.crypt.
.SH Mount options
.TP
\fBdm\-wait\fP
Wait for udev to create /dev/mapper/\fIname\fP after calling cryptsetup(8).
.TP
\fBdm\-timeout=\fP\fIseconds\fP
Wait at most this many seconds before giving up. The default value is 5
seconds.
.SH Authors
This manpage was originally written by Bastian Kleineidam <calvin@debian.org>
for the Debian distribution of pam_mount (libpam\-mount) but may be used by
others.

See /usr/share/doc/packages/pam_mount/AUTHORS for the list of original authors
of pam_mount.
