.TH mount.crypt 8 "15 June 2004"
.SH NAME
mount.crypt - mount a dm\-crypt encrypted volume
.SH SYNOPSIS
\fBmount.crypt\fP \fIdevice\fP \fIdirectory\fP [\fB\-o\fP \fIoptions\fP]
.br
\fBmount.crypt\fP {\fB\-h\fP|\fB\-?\fP}
.SH OPTIONS
.TP
\fB\-o\fP \fIoptions\fP
set the mount options
.TP
\fB\-h\fP, \fB\-?\fP
display help
.SH MOUNT OPTIONS
.TP
\fBdm-wait\fP
Wait for udev to create /dev/mapper/\fIname\fP after calling cryptsetup(8).
.TP
\fBdm-timeout=\fP\fIseconds\fP
Wait at most this many seconds before giving up. The default value is 5
seconds.
.SH AUTHOR
This manpage was originally written by Bastian Kleineidam <calvin@debian.org>
for the Debian distribution of pam_mount (libpam\-mount) but may be used by
others.

See /usr/share/doc/packages/pam_mount/AUTHORS for the list of original authors
of pam_mount.
