.TH umount.crypt 8 "15 June 2004"
.SH NAME
umount.crypt - unmount a dm\-crypt encrypted volume
.SH SYNOPSIS
\fBumount.crypt\fP \fIdirectory\fP
.SH AUTHOR
This manpage was originally written by Bastian Kleineidam
<calvin@debian.org> for the Debian distribution of libpam\-mount but
may be used by others.

See /usr/share/doc/packages/pam_mount/AUTHORS for the list of original authors
of pam_mount.
